"""Flexible template correction and composable averaging-matrix decisions."""

from .decisions import (
    MOTION_METADATA_KEY,
    AveragingMatrixBuilder,
    CandidateScoringMode,
    CandidateScoringPolicy,
    CorrelationMode,
    CorrelationPolicy,
    DirectionalQuota,
    MatrixDecisionError,
    MatrixDecisions,
    MatrixMetadata,
    MotionEligibility,
    MotionEpochMetadata,
    SamplingMode,
    SamplingPolicy,
    TargetPolicy,
    TemplateSizeMode,
    TemplateSizePolicy,
    TemporalDistanceUnit,
    WeightingBasis,
    WeightingKernel,
    WeightingPolicy,
)
from .flex import Flex, FlexCorrection

__all__ = [
    "MOTION_METADATA_KEY",
    "AveragingMatrixBuilder",
    "CandidateScoringMode",
    "CandidateScoringPolicy",
    "CorrelationMode",
    "CorrelationPolicy",
    "DirectionalQuota",
    "Flex",
    "FlexCorrection",
    "MatrixDecisionError",
    "MatrixDecisions",
    "MatrixMetadata",
    "MotionEligibility",
    "MotionEpochMetadata",
    "SamplingMode",
    "SamplingPolicy",
    "TargetPolicy",
    "TemplateSizeMode",
    "TemplateSizePolicy",
    "TemporalDistanceUnit",
    "WeightingBasis",
    "WeightingKernel",
    "WeightingPolicy",
]
